### ISSUE TITLE
Problem in getting records

### ISSUE THREAD

**Issue by SyedAkbarAli** [MohammedTaha/MCC201-Feb2015#1]
Dear Sir Taha, 
I took notes of your last class, and based on that I replicated this same code myself, and deployed successfully at https://sms-6037.herokuapp.com/addStudent on Monday/Tuesday.

Since then, I'm trying to make a list of students appear at https://sms-6037.herokuapp.com/

In dbFuncs.js, I added following lines below your saveStudentInDB(), I'm getting students data using find():

exports.findAllStudentsInDB = function(){
    var deferred = q.defer();
    mdlStudent.find({}, function(err, students){
        if(err) {            deferred.reject();            console.log(err);        }
        else    {           deferred.resolve();        }
    });
    return deferred.promise;
};

In api.sms.js, following your code: router.post('/addStudent'... , I added following lines to call the above function findAllStudentsInDB(), as follows:

router.get('/', function(req, res, next) {
    var students = dbFunctions.findAllStudentsInDB()
    .then(
        function(){res.send({status:true, students:students});},
        function(){res.send({status:false, students:{}});}
    );
    console.log("Got Students:");
    console.log(students);
});

Here, I'm getting students object with students data loaded from my mongoLab database.

Now, problem is that I'm unable to pass this Students object to the Student Sevice in srvSMS.js. 
In srvSMS.js following your code of this.saveStudent(), I added following lines to getAllStudents():

```
this.getAllStudents = function() {
    var deferred = $q.defer();

    $http.get("/api/")
        .success( function(response){ deferred.resolve(); this.students = response.students; } )
        .error(   function(){ deferred.reject();  } );

    return deferred.promise;
};
```

I've tried a lot since monday, but no success. At last, now I ask you to help me out.

Sir, kindly suggest what changes should I make in:
a) srvSMS.js - this.getAllStudents()
b) api.SMS.js - router.get('/'

and whatever changes are needed, with big thanks to you in advance.

Best regards

**Comment by MohammedTaha** [comment]
@SyedAkbarAli you are doing good Masha Allah, actually there are just some minor mistakes. Hope the following will help you out, further more we can discuss the details or confusions tomorrow Insha Allah.

``` javascript
exports.findAllStudentsInDB = function(){
    var deferred = q.defer();
    mdlStudent.find({}, function(err, students){
        if(err) { 
            console.log(err); 
            deferred.reject(); 
        }
        else { 
            // students --> the second parameter of .find's callback, actually these are records from Database
            deferred.resolve(students); 
        }
    });
    return deferred.promise;
};
```

in routes 

``` javascript
router.get('/', function(req, res, next) {
    var students = dbFunctions.findAllStudentsInDB()
    .then(function(studentRecords){
            // studentRecords => this studentRecords is what we passed to findAllStudentsInDB's resolve function.
            console.log("Got Students:");
            console.log(studentRecords);
            res.send({status:true, students : studentRecords});
        },
        function(){
            res.send({status:false, students: null});
        });
});
```

at angular service 

``` javascript
this.getAllStudents = function() {
    var deferred = $q.defer();
    $http.get("/api/")
        .success( function(response){ 
            //this.students = response.students; // on saying this.student you are introducing a field named students in service's scope. 
            //Since you are using promises you dont need to do this.
            deferred.resolve(response.students); 
            // now on calling MY_SERVICE.getAllStudents().then(function( STUDENTS_RECORDS_FROM_SERVICE ){ }) in your controller you can access all records sent from server
        })
        .error(function(){ 
            deferred.reject();  
        });
    return deferred.promise;
};
```

**Comment by SyedAkbarAli** [comment]
Dear Sir Taha,
I changed smsLandingPage.html as follows:

```
<h2>SMS: Landing Page</h2>
<table ng-init="getStudents()">
    <tr ng-repeat="std in students">
        <td>{{std.name}}</td>
        <td>{{std.age}}</td>
    </tr>
</table>
```

and its controller, ctrlSMSLandingPage, as follows:

app.controller('ctrlSMSLandingPage', function($scope, srvSMS) {
    $scope.students = {};
/\*    $scope.students = srvSMS.getAllStudents();*/
    $scope.getStudents = function() {        $scope.students = srvSMS.getAllStudents();    };
});

**Comment by SyedAkbarAli** [comment]
Dear Sir Taha,

I'm extremely happy to see your reply.

I was so sad to not overcome this lake of knowledge, i.e. passing students as deferred.resolve(students), although I saw it in book several times during the whole week.

I'm completely satisfied with your excellent and timely response.

Sir, please ignore my second reply, that's the old code, I thought to share with you before receiving your reply, but your reply came to me after I posted this. So, I'll update my code as per your instructions, and inform you in evening, right now I've to go to Urdu Bazar. If you like, I can get some books for you too.

**Comment by MohammedTaha** [comment]
:) thank you so very much bro.
